### ISSUE TITLE
To-fix: Unconnected Major Japan

### ISSUE THREAD

**Issue by Rub21** [mapbox/mapping#115]
**Task** http://osmlab.github.io/to-fix/#/task/unconnectedjapan

Unconnected major issues are motorable roads that end near another road but not connected to it. This could be because of:
- User error in creating proper junction for ways (fixable)
- User error in tracing the full road till the junction (fixable)
- Incomplete tracing because road connection not visible in imagery (requires survey)
- No road connection because of a wall or barrier (ignore)

**Task coverage**
- Japan

**Source**
- OSM inspector

**Mapping source**
- Bing
- Mapbox Satellite
- `http://{switch:a,b,c}.gps-tile.openstreetmap.org/lines/{z}/{x}/{y}.png`, Always use the GPS layer to see if the Satellite images are offset. 

**Timeline**
-  31 August issue count: 1,102

![image](https://cloud.githubusercontent.com/assets/1152236/9582970/422b42fa-4fce-11e5-82f2-5ce425201e32.png)

- @mapbox/team-data  will work on this challenge from 31 August.

**Instructions**
- Join disconnected roads and junctions verifiable from satellite imagery
- Do not make connections where there is a possibility of a fence or barrier in between the roads
- If editing in a actively mapped area, add a note instead of making a fix
- Check object history (ctrl+h) to understand why the previous user did not make a connection

**Note:**
- If you find roads to align, jump on this.
- If you find duplicates road,  check out the tag in both road and merge the tags in one road, if there are some conflicts on tags, figure out the last edition date on both roads, always prevails last edition date. .
- If you find places where missing roads,  could add those roads. 
- Before to upload the changes, do a validation in JOSM. 

**Tips and tricks**
- Use [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin) and read the [JOSM-Shortcuts](https://github.com/mapbox/mapping/wiki/JOSM-Shortcuts)
- You can select these nodes and merge them(m)
![image](https://cloud.githubusercontent.com/assets/1152236/9583099/06f28d82-4fcf-11e5-84a5-94697d194e62.png)
- Select the node and press (j) to join it to the nearby way
![image](https://cloud.githubusercontent.com/assets/1152236/9583155/525a7c4e-4fcf-11e5-8f20-28845f6a203a.png)

#### Resources
- https://github.com/mapbox/mapping/wiki/Working-with-To-fix

cc. @mapbox/team-data @lxbarth @aaronlidman

**Comment by planemad** [comment]
**Update**
- 09/07: Task updated. 770 issues remaining which team-blr will work on.

cc @mapbox/team-data

**Comment by nikhilprabhakar** [comment]
In some cases, there seems to be duplicate roads exactly on top of the existing roads.
![duplicate_roads1](https://cloud.githubusercontent.com/assets/11845908/9712307/674817ea-5567-11e5-9344-ddd9a71fdbe2.gif)


You can make it out because the node looks a bit more thicker like the below unlike an ordinary merged node.
![screen shot 2015-09-07 at 1 10 54 pm](https://cloud.githubusercontent.com/assets/11845908/9711538/f9df3b48-5561-11e5-83be-cd0596f54f50.png)

In doubt you could check whether there is a duplicate trace on top of a road by selecting the road and holding alt key(option key in Mac) to toggle between the roads in case there is a duplicate road. So that deleting the smallest part will become an easy task.

![toggling the roads](https://cloud.githubusercontent.com/assets/11845908/9712406/042e15be-5568-11e5-83d1-d64675153600.gif)

@mapbox/team-data

**Comment by planemad** [comment]
**Progress**
- 09/07: 7 members of team-blr cleared the 770 issues in 90 minutes.

**Comment by shvrm** [comment]
:rocket:
