### ISSUE TITLE
Tagging Delhi & Mexico City railway networks

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#134]
Delhi and Mexico city have large metro railway networks, but the stations lack a `network=` tag that is helpful for adding the metro logo for the station icons.

**Task** Add relevant `network=` tags to the `railway=station` and `railway=subway_entrance` of the Delhi and Mexico city metro network.

- [x] Delhi
- [x] Mexico City

### Delhi Metro
As per [talk-in proposal]() we can use `network=DMRC` for Delhi Metro. You can use the [Delhi Metro system map](http://www.delhimetrorail.com/Zoom_Map.aspx) for reference and [Overpass](http://overpass-turbo.eu/s/ctK) to check the progress on OSM.

![screenshot 2015-11-05 18 13 41](https://cloud.githubusercontent.com/assets/126868/10968701/f6156efa-83e8-11e5-87fb-ee8dd34f20a7.png)
*Stations on the yellow line are already tagged, Other lines and subway entrances pending*

@chtnha can you hit this out today for Delhi?

cc @mapbox/team-data

**Comment by chtnha** [comment]
I and @aarthykc together added `network=DMRC` for Delhi metro. 
![delhi_metro](https://cloud.githubusercontent.com/assets/6770741/10971550/da894d5c-83fa-11e5-99f5-7f956ab3921f.png)

@planemad @mapbox/team-data

**Comment by planemad** [comment]
@chtnha @aarthykc excellent! Just reviewed the edits, made [one correction](https://www.openstreetmap.org/changeset/35103650). We're done for Delhi.

**Comment by Rub21** [comment]
@planemad @chtnha @aarthykc I  added `network=STC Metro` for mostly of railway in  Mexico City: http://www.openstreetmap.org/changeset/35105751  http://overpass-turbo.eu/s/cul , but it is not completed yet,  because I found other tag   `network=Tren Ligero` 
![image](https://cloud.githubusercontent.com/assets/1152236/10975101/379660d6-83b3-11e5-82c8-316eed9e206e.png)


![image](https://cloud.githubusercontent.com/assets/1152236/10974927/379b1b18-83b2-11e5-88f2-de2e50ae0a34.png)

I will figure out on this.

**Comment by Rub21** [comment]
About the previus  commnet https://github.com/mapbox/mapping/issues/134#issuecomment-154120244 we leave those as they are.

We're done for Mexico City!

**Comment by planemad** [comment]
:+1: @Rub21
