### ISSUE TITLE
"islands minor highways" breaking data in the UK

### ISSUE THREAD

**Issue by systemed** [mapbox/mapping#186]
We're seeing problem with "islands minor highways" edits in the UK.

In the UK it's typical that a farmer's private bridge over a canal (often 200+ years old) is tagged as highway=track, bridge=yes, layer=1.

The bridge should _not_ be connected to the footpath (towpath) under the bridge, because it's for private use by the farmer only and there is no physical connection. If it's connected to anything it should be to an adjacent farmland landuse, but I wouldn't waste any time on doing that. highway=track does not imply public access in the UK.

Unfortunately we're seeing edits like http://www.openstreetmap.org/changeset/39449534 where the changeset comment is "Add missing turn lanes from satellite imagery in Dallas and Fort Worth" (?) and the mapper has completely deleted the towpath (http://www.openstreetmap.org/way/327119715/history).

Report from IRC:

````
16:41 trigpoint: SomeoneElse: I am just reverting the 2 changesets, the towpath 
had originally been drawn under the bridge and he moved it into the field to 
connect it to the bridge
16:44 trigpoint: And when deleting the towpath, drew 'made up' tracks to connect 
the bridge and clear the error
````

cc @SomeoneElseOSM, @trigpoint

**Comment by planemad** [comment]
@systemed @SomeoneElseOSM @trigpoint thanks for bringing this up, its certainly a cause for concern that our process to avoid freshly edited areas is not scaling up smoothly. As an immediate fix, it makes sense to drop places like UK with a highly active mapping community from QA tools like to-fix completely as it is reasonable to assume map issues are there for a valid reason like above.

Will keep this ticket open, till we have removed UK from to-fix tasks.

--

A reminder to @mapbox/team-data to look at the most important aspects of http://wiki.openstreetmap.org/wiki/Mapbox#Data_Team_Guidelines : In case of doubt, **ask for local help rather than map incorrectly**.

**Comment by planemad** [comment]
@systemed @SomeoneElseOSM @trigpoint this has been fixed by @Rub21 in our upstream processing. Let us know if you continue to find issues.
