### ISSUE TITLE
Question regarding the Mapping turn lanes practice

### ISSUE THREAD

**Issue by baditaflorin** [mapbox/mapping#208]
I see that in Chicago some people are adding the info like this. 

At the intersection, we know the lane count, and also the direction for each lane.

But in the middle, we do not have any information. 

From my point of view, we should add the info even on the ways that do not have a direction, and only continue the road. 

![image](https://cloud.githubusercontent.com/assets/2330999/16686622/12bcba46-451c-11e6-8e3e-28d6cc17e992.png)

![image](https://cloud.githubusercontent.com/assets/2330999/16686576/cf7b07f6-451b-11e6-8935-6d1a41724172.png)

**Comment by planemad** [comment]
@baditaflorin @Abbe98 these are valid suggestions that we will try to incorporate in our next turn lane mapping projects. Somethings to note:
- Adding lane counts on every single segment of the road in a city is significant effort and can exponentially increase the time for the project
- Lane mapping should ideally be a seperate project from turn lane mapping since the focus is on different types of attributes, maybe its better we don't add lane counts while adding turn lanes as it causes the issues mentioned.

cc @Rub21 @Andygol @maning
