### ISSUE TITLE
Investigate and cleanup broken route relations

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#224]
From https://github.com/mapbox/mapping/issues/180#issuecomment-240295557, it looks like splitting roads for adding turn lanes has resulted in broken bus route and highway route relations in Phoenix and possibly other cities in US where turn lanes were added.

Tracking the investigation of the cause and progress on fixing the relations here.

Detected broken relations: [Spreadsheet](https://docs.google.com/spreadsheets/d/1zlkn7IB2QtQwmeE-UBcEoH8_7DD1N2mbaCqyiYC0PdE/edit#gid=343191480)

**Next actions**
- [x] @samely investigate reasons for breakage
- [x] @Rub21 update master list of relations that need fixing

cc @mapbox/team-data

**Comment by planemad** [comment]
@drkludge for https://github.com/mapbox/mapping/issues/180#issuecomment-241519316

**Retrieving version of a OSM object**
`http://www.openstreetmap.org/api/0.6/[node|way|relation]/#id/#version`
[OSM API Documentation](http://wiki.openstreetmap.org/wiki/API_v0.6#Version:_GET_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id.2F.23version)

- http://www.openstreetmap.org/api/0.6/relation/4499231
- http://www.openstreetmap.org/api/0.6/relation/4499231/40

**Comment by planemad** [comment]
@drkludge it would be great if you can document the cleanup workflow here, the team is happy to help repair this as per instructions.

@rickmastfan67 thanks for https://github.com/mapbox/mapping/issues/180#issuecomment-241685926 . In summary to avoid such a scenario:
- Hit `Update Modified (Ctrl+Alt+M)` before any upload to avoid possible relation conflict
- Always download in a new layer

Would you add anything to ^ ? Would it make sense to add a config option in JOSM to automatically do this before upload for certain mapping sessions?

**Comment by drkludge** [comment]
This work flow repairs missing data for a route that was damaged before MapBox started on the turn lane effort.  The end result is that I have a route back where I still need to add the new segments that were created during the way splitting for the turn lane information.  Adding back segments will take some judgement and the gap tool in JOSM's relationship tool.  I am guessing that I will want to find all the relationships that were modified by the MapBox team.  That way bus, highway, etc. routes can be reviewed. @Andygol's list of relationships may be a possibility but the spreadsheet was for a wide range of work.

1.I grabbed the relation number from either the OSM map by showing the map data or I used the [OSM wiki page with the route master and route children links to the relation numbers.](http://wiki.openstreetmap.org/wiki/Arizona/Maricopa_County/Public_Transport)

2.I copied the number, say, 4499230 into the operating systems cut/paste system.

3.I went to JOSM and used down load object or ctrl+shift+O as in Oh.
![image](https://cloud.githubusercontent.com/assets/1669057/17893441/91aa0528-68fa-11e6-8586-28bce539dc7a.png)
JOSM is able to fill in the relation number.  Since I picked the parent or master relation from the wiki, I selected "Download relation members".  That way I had just the north and south bound route relations.  I also wanted the relation data in the same layer so I did not select the "Separate Layer" check box.

4.I perfromed a File > Save As... operation to create a text .osm file.

5.At this point I point I have the create relation tag information.  I am sure there are other ways to get this but I also have the OSM XML header and the actual relation tag list.
`<relation id='4499230' timestamp='2016-06-02T13:54:43Z' uid='94578' user='andygol' visible='true' version='42' changeset='39734969'>`

6.I modified the relation tag to say it was modified via the `action='modify'` tag. It shouldn't matter but I put action tag between the relation id and timestamp tags.
`<relation id='4499230' action='modify' timestamp='2016-06-02T13:54:43Z' uid='94578' user='andygol' visible='true' version='42' changeset='39734969'>`

7.I went to the [geofabrik.de raw download page for Arizona ](http://download.geofabrik.de/north-america/us/arizona.html#) and picked several months back.  I started with the the arizona-160801.osm.pbf file but noticed that this did not solve the problem.  In the case of the 7th Street routes, the route was gutted before MapBox added turn lanes.

8.I ran the pbf file through osmosis. 
```
set MAINCLASS=org.codehaus.classworlds.Launcher
set PLEXUS_CP=\gis\apps\osmparse\osmosis-latest\lib\default\plexus-classworlds-2.4.jar;\gis\apps\osmparse\osmosis-latest\lib\default
SET EXEC=java %JAVACMD_OPTIONS% -cp "%PLEXUS_CP%" -Dapp.home="\gis\apps\osmparse\osmosis-latest" -Dclassworlds.conf="\gis\apps\osmparse\osmosis-latest\config\plexus.conf" %MAINCLASS%  -v --read-pbf file=\gis\apps\osmparse\arizona-160401.osm.pbf --buffer --write-pgsql-dump enableBboxBuilder=yes enableLinestringBuilder=yes  nodeLocationStoreType="TempFile" directory=.

%EXEC%
```

9.I used the relation_members.txt file and searched for the 4499230 relation with /^4499230 in vim.

![image](https://cloud.githubusercontent.com/assets/1669057/17894549/945ba48a-68fe-11e6-98b8-87e7780f0971.png)


10.I set a mark of **a**, ma, at the beginning of the list of members and set a mark of **b**, mb, at the end of the list in vim.

11.The marks allowed me to regex the member list into what an .osm file should have. The 'a and 'b in the regex line references the two marks **a** and **b** respectfully.
`:'a,'b s/^\([0-9]*\)^I\([0-9]*\)^I\(.\)^I\(.*\)^I.*$/    <member type='way' ref=
'\2' role='\4' \/>/
`  I am out of time now but will come back and document the regex.
![image](https://cloud.githubusercontent.com/assets/1669057/17894753/52171568-68ff-11e6-8888-009a76ad5d93.png)

12.I cut the modified section from the osmosis relation_members.txt file and pasted the data into the members section of the file created in steps one to seven.

13.I saved the text file; opened the file in JOSM via a new layer; checked the data with data on the server; and finally uploaded the repaired relation.

**Comment by samely** [comment]
@rickmastfan67 love your tips, this should definitely part of our workflow.

@planemad as I [commented](https://github.com/mapbox/mapping/issues/180#issuecomment-240781132) it's not about the knife tool, but about updating data before uploading. We broke relations because we added `turn:lanes` in roads that belong to the same relation.

I've filtered again all relations and created a new [spreadsheet](https://docs.google.com/spreadsheets/d/1XxXkHhq385X_ttiNWn2hlnCoM6QSGWVPGWyVsJDeZts/edit#gid=0) based on the @Andygol 's one. It contains the list of relations we touched while mapping `turn:lanes` and `turn:restrictions`.

@drkludge I also recorded the [workflow we are following to fix relations](https://gist.github.com/samely/1c36aa97a3f62598541cdd4c72b2841b) It would be great if you try it and suggest any improvement.

**Comment by drkludge** [comment]
I added a comment about the spreadsheet status column, the visual gap, and right click zoom to segment menus in the workflow ticket.

**Comment by samely** [comment]
@drkludge thanks for your comment. We know we need to review more than once the relation and that's going to be with the validation process. Do you suggest anything else?

**Comment by maning** [comment]
I see no next actions here, closing.
