### ISSUE TITLE
Updating turn restrictions in Germany using Mapillary

### ISSUE THREAD

**Issue by krishnanammala** [mapbox/mapping#226]
### Goal
- To update missing [turn-restrictions](http://wiki.openstreetmap.org/wiki/Relation:restriction) in 5 German cities using Mapillary as the source
- Cities: Berlin, Stuttgart, Wolfsburg, Frankfurt, Munich
### Task Workflow:
1. Use the [OSM navigation map](https://github.com/mapbox/mapping/wiki/Mapping-guide-for-adding-turn-restrictions-using-Mapillary#using-osm-navigation-map) to find the missing turn restrictions.
2. [Follow Turn restrictions in Germany](https://github.com/mapbox/mapping/wiki/QA-on-mapping-turn-restrictions#germany)
3. Based on the detected turn restrictions from `OSM navigation map`, add an [**OpenStreetMap note**](http://wiki.openstreetmap.org/wiki/Notes) on places where there is missing turn restrictions or any questions related to it.

---

![germanytr](https://cloud.githubusercontent.com/assets/11845908/18001092/c25b785e-6b9e-11e6-96c1-6a33b000b7c4.jpg)

**Team** : @mapbox/team-data 

**Timeline** : 4 days (Estimate)

**Tagging guidelines** 
- [Absolute turn restrictions](http://wiki.openstreetmap.org/wiki/DE:Relation:restriction) 
- [Conditional turn restrictions](http://wiki.openstreetmap.org/wiki/DE:Conditional_restrictions)

**Data sources**
- Mapillary detected traffic signs via [OSM navigation map](http://mapbox.github.io/osm-navigation-map/#10.01/52.5068/13.4243) and JOSM plugin
- Bing/Mapbox satellite imagery for cross verification of photograph location/bearing and turn lane markings
## Process
- Two mappers can work at one city together and work at different parts of the city to avoid conflict and also mention start and end time in the spreadsheet.
- The number of already mapped turn restrictions is given in the spreadsheet. Use the Overpass queries given in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Q82lpJURXYGIkSth20ZVyy9t0W6yqSeeXYXEcKTtezg/edit#gid=0) to get the edit count after a city is completed
- Hackpad link: https://hackpad.com/-Missing-Turn-restrictions-X3FPoa4Bstr
### JOSM Setup
- **Plugins:**
  - [Mapillary plugin](http://blog.mapillary.com/update/2015/06/25/josm-mapillary.html) - to evaluate the data completeness and accuracy.
  - [Turn-Restriction plugin](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/Turnrestrictions) - to validate the turn restrictions that is already mapped.
- **Paint Styles**
  - [Traffic Signs](https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss) : JOSM Preferences -> Map Settings -> traffic signs
### Context of OSM note:
- What turn restriction is missing?
- From and to road?
- Navigation map link of missing turn restriction.

```
Hello,
Is there a `no_right_turn` from am fichcenberg road?

Please refer to traffic sign captured on Mapillary: [Navigation map link]
```
### Stats:

| Date | Cities | Reviewed | Valid | Redundant | Invalid | Notes | Resolved |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 23-Aug-16 |  |  |  |  |  | 8 |  |
| 29-Aug-16 | Berlin, Stuttgart, Wolfsburg | 138 | 41 | 69 | 14 | 13 |  |
| 30-Aug-16 | Berlin, Stuttgart | 297 | 59 | 191 | 34 | 13 |  |
| 31-Aug-16 | Berlin | 433 | 66 | 302 | 31 | 29 |  |
| 1-Sept-16 | Berlin | 143 | 16 | 87 | 31 | 10 | 42/73 |
| 6-Sept-16 | Munich,Frankfurt | 509 | 107 | 309 | 54 | 26 |  |
| 7-Sept-16 | Munich,Frankfurt | 434 | 81 | 267 | 68 | 13 | 15/39 |

cc @mapbox/berlin @mapbox/team-data

**Comment by maanyaumashaanker** [comment]
### Case 1:
![screen shot 2016-08-29 at 12 16 03 pm](https://cloud.githubusercontent.com/assets/19161907/18043015/a52fa994-6de2-11e6-942c-e07b9e7f2e82.png)

In this [case](http://mapbox.github.io/osm-navigation-map/#18.36/52.43877/10.80862) no turn restriction has been added but the mapillary shows two boards with `no_left_turn` and `only_left_turn`. Does this indicate a turn restriction or does it imply turn lanes.

**Comment by bsrinivasa** [comment]
## Case 2:

Similar to @maanyaumashaanker's case-1, here is a mapillary detection where it is not yet been possible to figure out on how to deal with this.
Here are images to represent the case.

![screen shot 2016-08-29 at 2 07 46 pm](https://cloud.githubusercontent.com/assets/17143802/18046482/bd3c8a76-6df5-11e6-85fe-91baf14a8e3b.png)
*Fig-1*


![thumb-2048](https://cloud.githubusercontent.com/assets/17143802/18046483/bd6670d4-6df5-11e6-8b53-703be95d554a.jpg)
*Fig-2: Mapillary image*

#### Details:
In this case, the junction has 3 roads viz L1192, L1192, and L1208a. The mapillary image from fig-1
has two turn restriction board (in [context](https://github.com/mapbox/mapping/wiki/QA-on-mapping-turn-restrictions#turn-restriction-signs-of-germany-and-what-it-means) of Germany) which has not been mapped in OSM. But there is relation `only_straight_on` which seems to be invalid for the road. I would like to hear suggestions on the following questions,
Is there a need to add a turn restriction at this junction?  If yes, how do we add turn restrictions based on lanes?

Reference: http://mapbox.github.io/osm-navigation-map/#18.99/48.69039/9.17641

**Comment by freenerd** [comment]
I did some Googling:

- https://de.wikipedia.org/wiki/Fahrbahnmarkierung (german wikipedia is really exhaustive)
- http://www.sicherestrassen.de/VKZKatalog/Frameaufbau.htm?http://www.sicherestrassen.de/VKZKatalog/KatMarkBildsuch.htm (german website with cases)
- https://www.gesetze-im-internet.de/stvo_2013/anlage_2.html (german law for traffic, see _Abschnitt 9_ for markings)
- https://www.gesetze-im-internet.de/stvo_2013/anlage_3.html (german law for traffic, see _Abschnitt 8_ for markings)

My current understanding:

- If there is a marker on the ground, you need to follow it if you are in that lane
- Often markers are accompanied with turn-lane signs (the blue arrows)

In both examples, the turn restriction signs match the lane markings. Thus you can assume that the sign is valid only for it's respective lanes. In both examples the combined turn restrictions for all lanes do not actually restrict any of the turns. Therefore I suggest to not map any turn restrictions, but only the lanes with their respective directions.

One corner-case I'm unsure about are u-turns. In Germany there is only a traffic sign for denying u-turns, but none for allowing it explicitly. Thus u-turns should be allowed in both cases here.

**Comment by krishnanammala** [comment]
We have reviewed all the Mapillary detected turn restrictions on [OSM navigation map](http://mapbox.github.io/osm-navigation-map/#11/52.4114/10.7796) in Wolfsburg. 
Turn restrictions that we came across were either already mapped or redundant for us to leave notes for the community to verify and map.

cc @mapbox/team-data

**Comment by jojo4u** [comment]
The analysis from freenerd is correct for the two cases.

About u-turns: It's some special form of turning left (widely considered "turning left two times"), but have to be extra-careful and yield to all traffic.

Repeating my [list from the diary](https://www.openstreetmap.org/user/nammala/diary/39345), turning (including u-turn) is not allowed if: 
1. A sign forbids it
2. A "Intersection arrows" is present and does not point in your direction
3. A "Restricted zone" or a "solid center line" will be crossed

**Comment by poornibadrinath** [comment]
I came across this restriction signage, where it is mentioned one can go `straight or right`. But there is a red slash mark over the signage, which could be interpreted as the turn restriction isn't valid anymore. 

![image](https://cloud.githubusercontent.com/assets/17887418/18127088/e24ffb34-6f9b-11e6-80b8-1b8774d5eaac.png)

![image](https://cloud.githubusercontent.com/assets/17887418/18127135/1858003c-6f9c-11e6-8729-cfc48afe15a5.png)

I would like some suggestions on how this restriction signage could be read and understood. Is this restriction not valid or does it mean something else?

**Comment by freenerd** [comment]
Red or yellow tape over traffic signs invalidates the sign. Usually these are temporary restrictions due to construction sites. A more extreme example is not only signs being changed, but also lane markings:

![sddb09](https://cloud.githubusercontent.com/assets/25713/18127429/ab2e53a0-6f80-11e6-90ba-3e0c374ce34d.jpg)

@poornibadrinath in your case, I actually know the street, because it's in Berlin. From memory I don't can't think of a good reason why there should be a turn restriction on that point. To be super sure I'd need to pass by there again though. I think for now it's safe to skip this turn restriction.

**Comment by poornibadrinath** [comment]
@freenerd Thank you so much. I will save the link just to be sure in case we might have to check it once again. :)

**Comment by krishnanammala** [comment]
We have reviewed all Mapillary detected turn restrictions on [OSM Navigation map](http://mapbox.github.io/osm-navigation-map/#10.79/48.7794/9.1773) in Stuttgart. Totally we added **5** OSM notes for missing turn restrictions and **4** got resolved by the community as of now 🎉 .

We are going to continue reviewing detected turn restrictions from Mapillary in Berlin.

cc @mapbox/india-office

**Comment by poornibadrinath** [comment]
I came across this situation where there are two different turn restrictions detected at two different positions. There are two separate roads for which each of the restriction could apply:
1) There is a residential road near the restriction board which says `straight or right`
2) There is a one way from left to right direction near the restriction board which says `only straight on`

![pasted_image_01_09_16_3_45_pm](https://cloud.githubusercontent.com/assets/17887418/18164088/c7473b52-705b-11e6-9d33-c2c938fd5d86.png)

![image](https://cloud.githubusercontent.com/assets/17887418/18163843/892ea8ce-705a-11e6-9a15-3bb7edf45eff.png)

![image](https://cloud.githubusercontent.com/assets/17887418/18163864/a9f6ae30-705a-11e6-9874-a766540a8391.png)

* So in this case, does the no left restriction applies for the residential road that is linking two primary highways, and hence it is a valid turn restriction that needs to be added or 
* It applies to the one way a little ahead saying only straight on, since it is a one way which makes it invalid. 

The reason for this confusion is, on the right side, I can see a lot of red and white barriers, which could technically mean no entry. 

I would like some suggestions as to how one would interpret this scenario and where the turn restriction should be added.

**Comment by bsrinivasa** [comment]
I found this `only_straight_on` turn restriction while reviewing in Berlin. This has a message in German language pasted on the sign board. The message that is visible is `Brustelien-fahrzeuge frei`. I tried with Google translation and this was the output `Brustelien vehicles free` . 

![screen shot 2016-09-01 at 3 22 41 pm](https://cloud.githubusercontent.com/assets/17143802/18164436/78d7356a-705d-11e6-80c3-58e6f94cf4be.png)

![screen shot 2016-09-01 at 3 24 38 pm](https://cloud.githubusercontent.com/assets/17143802/18164437/78ddc0b0-705d-11e6-81bd-6c1003196149.png)


I would like some suggestions on how this restriction signage could be read and understood. Is this restriction not valid or does it mean something else?

OSM Navigation Map link: http://mapbox.github.io/osm-navigation-map/#19.98/52.53583/13.37662

**Comment by freenerd** [comment]
@poornibadrinath can you post links?

@bsrinivasa it means "construction site vehicles exempt". looks temporary as well, so likely nothing we want to map

**Comment by poornibadrinath** [comment]
@freenerd link to the navigation map is posted at the end.

**Comment by bsrinivasa** [comment]
@freenerd Thank you for clarifying this.

**Comment by freenerd** [comment]
@poornibadrinath I think this photo captures the state correctly: 

![](https://cloud.githubusercontent.com/assets/17887418/18164088/c7473b52-705b-11e6-9d33-c2c938fd5d86.png)

There are two cross-streets, one coming from the right and one coming from the left. 

- The one from the right is a temporary construction site in the mapillary picture. The goal of the blue turn restriction with `only straight or right turn` is to make sure people don't do u-turns to the left. I assume the construction site is only temporary, thus the turn restriction should be added.
- The one from the left is behind the first intersection, thus needs a new sign. It's a `only straight` sign because drivers can't see that it's a one-way street coming from the left. From a mapping perspective, I do not know if a turn restriction should be added. OSRM won't route into a one-way street so the current state might be okay. Since the one-way street also extends over the split road, U-Turns are not possible either. I see two arguments for adding a turn restriction:
  1. Clear matching to the signs
  2. If somebody ever decides to change the one-way street within the split road, a turn restriction would still prevent u-turns

**Comment by poornibadrinath** [comment]
@freenerd Thank you so much for the help!

**Comment by krishnanammala** [comment]
We have completed reviewing all detected mapillary turn restrictions on [OSM Navigation map](http://mapbox.github.io/osm-navigation-map/#10.01/52.5068/13.4243) in **3** cities i.e., Berlin, Stuttgart and Wolfsburg. We managed to add 73 [OSM notes](https://hackpad.com/-Missing-Turn-restrictions-X3FPoa4Bstr) for the community to verify and add the possible turn restrictions, out of which 38 notes are resolved as of now.

Now, we would like to jump onto 2 other cities in Germany i.e., Frankfurt and Munich and we would like to follow the same [workflow](https://github.com/mapbox/mapping/issues/226#issue-173458682) for the above 2 cities.

[OSM Navigation map](http://mapbox.github.io/osm-navigation-map/#9.71/48.1205/11.5697)

cc @mapbox/india-office

**Comment by krishnanammala** [comment]
We have completed reviewing all Mapillary detected turn restrictions on [OSM Navigation map](http://mapbox.github.io/osm-navigation-map/#9.71/48.1205/11.5697) in Frankfurt & Munich. We managed to add **39** [OSM notes](https://hackpad.com/-Missing-Turn-restrictions-X3FPoa4Bstr) for missing turn restrictions in these 2 cities, out of which **6** got resolved as of now.

[Stats](https://github.com/mapbox/mapping/issues/226)

cc @mapbox/team-data

**Comment by krishnanammala** [comment]
As a part of making OpenStreetMap more navigable and accurate for routing, We started updating Missing turn restrictions in 5 cities in Germany i.e., Berlin, Stuttgart, Munich, Frankfurt, Wolfsburg.

In the process, we added **112** [OSM notes](https://hackpad.com/-Missing-Turn-restrictions-X3FPoa4Bstr) for the probable missing turn restrictions for the community to verify and map. As of now, **102** notes were resolved out of which **60** notes were resulted in adding data to the map. Still **10** OSM notes to be resolved.

* Posted a Diary [updating navigation data in Germany](http://www.openstreetmap.org/user/nammala/diary/39468)
* Posted a Diary on [progress update](http://www.openstreetmap.org/user/nammala/diary/39468) also a [comment](http://www.openstreetmap.org/user/nammala/diary/39509#comment36341) .

Will track the remaining OSM notes and keep posted. 👍 

Closing the ticket for now.
