### ISSUE TITLE
Updating Missing Exit numbers & Destinations in Germany

### ISSUE THREAD

**Issue by nikhilprabhakar** [mapbox/mapping#228]
In an effort to make OpenStreetMap more navigable and accurate in guidance, we have previously reviewed on [updating turn restrictions in Germany.](https://github.com/mapbox/mapping/issues/226) We are now focussing on updating the missing exit numbers and destinations in these 3 Cities of Germany:

1. Berlin
2. Stuttgart
3. Wolfsburg

![krishna_exit_destinations](https://cloud.githubusercontent.com/assets/11845908/18197110/2d263c36-7113-11e6-9ef2-a9d4187fa10e.jpg)

**Features to verify:** Highway Exit Numbers and Destinations

**Estimated features to verify:** To be calculated

**Estimated time to verify:** To be calculated

**Sources:** We are only using [Mapillary](https://www.mapillary.com/) as the source to refer exit numbers and destinations.

### Workflow

**Tasking Manager**: **[Task Link](http://cfn-tasking-manager-staging-vpc-387856624.us-east-1.elb.amazonaws.com/project/22#task/4)**

**Hackpad link:** https://hackpad.com/Exit-and-destination-Germany-79XJYZkGnkR

In tandem with tasking manager, we are using [k1wiosm's](https://github.com/k1wiosm) [Checkautopista2 tool](http://k1wiosm.github.io/checkautopista2/?lat=52.4962&lon=-88.7256&z=5) to review each highway in the cities mentioned above. To understand how to use Checkautopista2 tool to map exit numbers and destinations, please refer to the [detailed workflow guide here](https://gist.github.com/krishnanammala/e7375fade10cbfad8d805557769db5b1). 

* Mark the highway as  **DONE** if it has been completely reviewed and if the resources to review the highway are not sufficient, comment on the task stating the reason: **No resources/ No Mapillary coverage.** 

  
**JOSM Filters:**
 These below filters can be used to ease work in JOSM editor.

* Filter out non road features with `boundary: | leisure: | landuse: | waterway: | amenity: | natural: | building:`

* Add inverse filter: `highway=motorway | motorway_link | trunk| trunk_link | primary | secondary | tertiary`

#### Outline for the OSM notes:

**For missing exits:**

`Hello,
Is there a missing Exit number for this Motorway_junction ?`
[Checkautopista2 link] 

**For missing destinations:**

` Hello,
Is there a missing Destination from this Motorway_junction ?`
[Checkautopista2 link] 

cc @mapbox/team-data

**Comment by joto** [comment]
I am looking at the image above. I am pretty sure the small "23" in the box you marked as `destination:ref` is not a ref but the exit number. Also note that in this image what you marked as `destination`, the "Buschkrugallee", is not the name of a *place*, but the name of a *road*. I haven't found anything in the wiki description of the `destination` tag to either allow or disallow this use.

**Comment by poornibadrinath** [comment]
I came across this situation where the motorway junction has an `exit_to` tag which says it's an exit to `Seestraße`, which is the name of the road. 

![image](https://cloud.githubusercontent.com/assets/17887418/18195845/969f090c-710b-11e6-9ea8-9ed54ee88733.png)

![image](https://cloud.githubusercontent.com/assets/17887418/18195858/aeff31d4-710b-11e6-9707-2ec4a781737f.png)

There is no `destination` tag added to the way and there is a mapillary image of a sign board which says `ref=111`, `Hamburg` on the side of the street, Seestraße. 

![image](https://cloud.githubusercontent.com/assets/17887418/18195890/dc4eba7e-710b-11e6-8b8f-4496c40f7b8b.png)

![image](https://cloud.githubusercontent.com/assets/17887418/18195951/3e9b6c72-710c-11e6-975a-5960cc85a47d.png)

Is this is a destination tag for this street? Because exit signages or boards do not look like this. Or is this just a sign board which says to reach `exit 111` which goes to Hamburg, take this way? 

@freenerd It would be great to have your suggestion on this particular situation. Should there be a destination tag added to this way? And why is street name added in the `exit_to` tag in the motorway junction instead of a place or another street name it leads to.

**Comment by nikhilprabhakar** [comment]
Thanks for the heads @joto, I have changed the image.

>  image what you marked as a destination, the "Buschkrugallee", is not the name of a place, but the name of a road. 

In that case, is there any specific way of tagging street names for destination or should we just use the `destination=*` tag itself?

**Comment by freenerd** [comment]
@poornibadrinath I'm not 100% sure I get the signs there correctly either. Here is what I think:

- The sign is placed on the off-ramp, so it's only valid after one is already gone from the A100 Autobahn.
- There is likely a sign already on the A100 Autobahn before, but I couldn't find it in the Mapillary imagery.
- The sign on the off-ramp has as destination the A111 Autobahn in the directions of Hamburg and Reinickendorf. `111` is definitely not an exit number, but the name of that other Autobahn. I guess `destination=A111 Hamburg` might be the right tag then???
- Since the sign is showing several directions, maybe the destination tags should be on the ways post-intersection, e.g. on the slip road to `Saatwinkler Damm`

All above is with a grain of salt, I'm really not sure what is best here.

**Comment by poornibadrinath** [comment]
@freenerd Thank you so much. Adding a note to confirm whether this destination sign is for this exit only.

**Comment by bsrinivasa** [comment]
![screen shot 2016-09-02 at 2 41 11 pm](https://cloud.githubusercontent.com/assets/17143802/18198839/5f3621a2-711b-11e6-8589-47f2a32f7f25.png)

![screen shot 2016-09-02 at 2 42 08 pm](https://cloud.githubusercontent.com/assets/17143802/18199027/402400b2-711c-11e6-83a7-d4a451605042.png)

I came across this case while reviewing this exit at Wolfsburg wherein both `node` and `way` has been tagged with a `destination=*`. 
2 Out of 3 exits that were reviewed, had extra 'values'(info) on the`node` when compared with the `way` and the other had the same value.

Since `destination=*`  tag is added only for the `way` (as per the [wiki](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_junction#Destination_of_the_exit) ), would the tag on the `node` be a redundant ?

Reference link: http://k1wiosm.github.io/checkautopista2/?id=5539603&lat=52.4623&lon=10.7371&z=17

I would like to hear your suggestions on this.

cc: @freenerd

**Comment by polarbearing** [comment]
Fixed osm-note 697945 via CS 41928807 regarding the Exit 1 on motorway 100 issue above.

**Comment by nikhilprabhakar** [comment]
As per the [workflow](https://gist.github.com/krishnanammala/e7375fade10cbfad8d805557769db5b1) followed to find the possible missing exit and destinations data, we have completed our review for Berlin, Stuttgart and Wolfsburg. We added one [OSM note](http://www.openstreetmap.org/note/697945) as a part of this task which got resolved by the  community.

As a next step, we are going to jump onto 2 other cities in Germany i.e., Frankfurt and Munich to update missing exit and destination data. We are going to use the same workflow that we used for Berlin, Stuttgart and Wolfsburg. Please find the link for the task and hackpad below.

**Task link:** http://cfn-tasking-manager-staging-vpc-387856624.us-east-1.elb.amazonaws.com/project/24

**Hackpad Link:** Hackpad link: https://hackpad.com/Exit-and-destination-Germany-79XJYZkGnkR


cc @mapbox/india-office @mapbox/berlin

**Comment by abhisheksaikia** [comment]
### Case of using `destination:lanes=*` tagging scheme

I found a `highway=motorway_junction` with the following associated mapillary image:

![screen shot 2016-09-08 at 3 31 49 pm](https://cloud.githubusercontent.com/assets/13744156/18345506/76b32c5e-75d9-11e6-9a7f-d03f9624d83a.png)

Assuming^^ the mapillary image denoted the destinations as `Eschborn;Kronberg;Schwalbach`, the associated `motorway_link` would normally be tagged with `destination=*` . But, in this case the main `motorway` is tagged with `destination:lanes=*` and there are no `destination=*` tags in the motorway_link (which is generally followed)

Checkautopista link: http://k1wiosm.github.io/checkautopista2/?id=15625&lat=50.1289&lon=8.5672&z=18
Destinations_per_lane Wiki: http://wiki.openstreetmap.org/wiki/Key:destination#Destinations_per_lane

**Comment by nikhilprabhakar** [comment]
The team [reviewed all the exit and destination numbers](http://cfn-tasking-manager-staging-vpc-387856624.us-east-1.elb.amazonaws.com/project/22) for the cities Berlin, Stuttgart, Wolfsburg, Frankfurt and Munich. We [added 2 notes](https://hackpad.com/Exit-and-destination-Germany-79XJYZkGnkR) and both got resolved thanks to the community.

No next actions as of now. Closing this ticket.

cc:// @mapbox/team-data
