### ISSUE TITLE
Adding missing buildings in Fort Worth and Dallas

### ISSUE THREAD

**Issue by jinalfoflia** [mapbox/mapping#297]
![sundance_christmas_tree_s](https://cloud.githubusercontent.com/assets/4470913/26457711/c3bfcce2-418e-11e7-97d1-6e9d3279c9c3.jpg)
_By Towerguy - Own work, Public Domain, https://commons.wikimedia.org/w/index.php?curid=5963773_

**Objective**: Improve OpenStreetMap basemap data by tracing buildings in Fort Worth and Dallas.  

**Tasks**:
[](http://tasks.openstreetmap.us/project/95)
- [Missing buildings in Fort Worth and Dallas](http://tasks.openstreetmap.us/project/95)

### Workflow

- Pick a task from the [Tasking Manager](http://tasks.openstreetmap.us/project/95).
- Load the Mapbox/Bing imagery to JOSM.
- Install [JOSM Buildings Plugin](https://www.mapbox.com/mapping/mapping-common-features/#buildings) for easy tracing.
- Inspect the imagery to find the missing buildings.
- Add only missing buildings.
- Ignore areas with cloud cover/ look at different imagery for those areas.
- Changeset comment: `Tracing missing buildings in Fort Worth and Dallas #https://github.com/mapbox/mapping/issues/297`
- Source: `Texas Orthophoto`

**Resources**:

- [Mapping common features using JOSM](https://www.mapbox.com/mapping/mapping-common-features/)

cc: @mapbox/map-squad

**Comment by maning** [comment]
Lets use the [Texas Orthophoto](https://josm.openstreetmap.de/mapsview?entry=Texas%20Orthophoto) (2017) instead of Bing (2014).  

![texas](https://cloud.githubusercontent.com/assets/353700/26482396/cf73c9a0-4204-11e7-88b6-429f67f1ee06.gif)

@abhisheksaikia can you update the TM imagery source?

WMS url: `wms:https://wms-txgi.tnris.org/login/path/ecology-fiona-poem-romeo/wms?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=texas_2017&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}`

**Comment by maning** [comment]
Community is planning an import for Fort Worth, we don't need to trace from imagery. Let's keep watch on the import progress and help the community if needed.

![screen shot 2017-05-29 at 07 25 33](https://cloud.githubusercontent.com/assets/353700/26534275/106ec6c0-4440-11e7-8b78-75f08a75727e.png)
