### ISSUE TITLE
QA tools in use

### ISSUE THREAD

**Issue by mvexel** [mapbox/mapping#325]
Hey folks. 

I am preparing for my MapRoulette talk at SOTM Japan next week and wanted to review the state of QA tools. A few questions:

* What tools are you guys using on a regular basis?
* Which QA tools have gained / lost the most value in recent years?
* What are some of the gaps / challenges you see in the OSM QA landscape?

Don't be afraid to bash MapRoulette :)

I appreciate your 💌.

**Comment by cliffordsnow** [comment]
Martijn,
**What tools are you using**
Mostly I use OSMI to find errors and use a local run geoserver to look at streets.

**Which QA tools have gained / lost...**
OSMI has been my main goto tool. I used to use the TIGER basemap in JOSM and iD but find it often out of date or just wrong. 

**What are some of the gaps / challenges you see in the OSM QA landscape?**
The one gap that needs filling is to categorize errors and then fix the root problem of the error. For example, I notice new mappers using abbreviated street names. (This is just an example, not necessarily the biggest problem) 

I've been trying to learn django to build a form to capture errors, just for new mappers. The goal is to see if we can get at the root cause and prevent the error in the first place. Tools like OSMI are great for identifying existing errors, but do nothing to prevent them from continuing.

**Comment by bikeoid** [comment]
What tools?

I use OSMI when I'm checking for a specific class of errors.   And monitoring changesets, and anything looking like I should check, I use OSMCHA.

MapRoulette has matured the most in the past 2 years for specific challenges.

**Comment by Carnildo** [comment]
**What tools are you guys using on a regular basis?**

Mostly the history view on the OSM website, and ACHAVI.  Eastern Washington/Northern Idaho is quiet enough that I can usually review every changeset manually.  Once or twice a year I'll do a sweep with Osmose to find things I missed, or mistakes I made in my own edits.

**Which QA tools have gained / lost the most value in recent years?**

Haven't been around enough years to say.

**What are some of the gaps / challenges you see in the OSM QA landscape?**

The biggest problem I see is single-target QA challenges, MapRoulette or otherwise.

Step 1 of any QA task is "engage brain", and the workflow involved in single-target challenges tends to discourage this.  People get into the routine of performing a set of actions that resolve the highlighted issue 95% of the time, and fail to think about the *meaning* of what they're doing.  For a recent example, someone doing a "fix isolated roads by connecting them" challenge "fixed" a building tagged as "highway=service" by tracing the driveway connecting that building to the road network, rather than by removing the erroneous tag.

QA tasks organized by area rather than by type tend to avoid this.  If the last highlighted problem was "highway intersecting building", and you're now being asked to resolve an "object tagged twice as node and way", it's harder to get into a mindless routine.

**Comment by planemad** [comment]
@mvexel thanks for collecting thoughts here, SOTM presentation is up http://2017.stateofthemap.org/2017/maproulette-is-evil/
