### ISSUE TITLE
language switcher should go to the same article instead of main page/dashboard

### ISSUE THREAD

**Issue by maning** [mapbox/mapping#337]
@Andygol please expand

**Comment by Andygol** [comment]
In a case when we are reading **Getting started** (https://www.mapbox.com/mapping/getting-started/) and wish to switch the language of the article (in Japanese, for example) we will get the main page of the mapping guide (https://www.mapbox.com/mapping/jp/) on that language instead of just switching the language of the article (https://www.mapbox.com/mapping/jp/getting-started/).

@maning
