### ISSUE TITLE
Turn restrictions based on Mapbox machine learning models

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapping#349]
We are releasing our initial turn restriction sign detections based on our internal machine learning models with more data to come in the future. Here is the raw data for the first batch of detections:

#### [GeoJSON](https://gist.githubusercontent.com/daniel-j-h/0cb2a156a503937d218a33036413e172/raw/582b21922e8956897c3ede4055c8b5e58ede46e3/initial-turn-restrictions.geojson)

Our internal machine learning models are based on Bing StreetSide's imagery for which Mapbox acquired the rights to contribute off of. We do not own the imagery and therefore are not allowed to make it available for the OSM community.

I will write up a [diary post](https://www.openstreetmap.org/user/daniel-j-h/diary/43242) with details in the coming days.

**Comment by daniel-j-h** [comment]
![map](https://user-images.githubusercontent.com/527241/35706413-a5619b62-0773-11e8-9f46-e5d38c9e4774.png)

**Comment by daniel-j-h** [comment]
Diary post:

https://www.openstreetmap.org/user/daniel-j-h/diary/43242

**Comment by GITNE** [comment]
Guys, before you run off mindlessly to the job, please be aware of what you are actually mapping: **Turn restrictions** or **traffic signs** denoting turn restrictions. In OpenStreetMap terms these are two totally different concepts!

* Traffic signs (`traffic_sign=*`) **denote** the **legal situation on the road**.
* Turn restrictions (`type=restriction`) **model** the **flow of traffic**.

Most importantly: **DO NOT** add default turn restrictions. This especially pertains to `restriction=no_u_turn` restrictions on single way junctions. Hence, do not add turn restriction relations with identical members in the `to` and `from` roles, like in this [**bad example**](). This kind of `restriction=no_u_turn` restriction is the **default**.

In these cases, if you still want to add data about this turn restriction to OSM—because it is veritably (via Mapillary etc) signed—then map with:

* [`traffic_sign=US:R3-4`](https://upload.wikimedia.org/wikipedia/commons/d/d1/MUTCD_R3-4.svg)[! or [`traffic_sign=US:R3-18`](https://upload.wikimedia.org/wikipedia/commons/a/a1/MUTCD_R3-18.svg) with a node on the way
* `direction=forward`/`backward` depending on way direction and the direction of traffic flow this traffic sign applies to

alternatively

* [`traffic_sign:forward=US:R3-4`](https://upload.wikimedia.org/wikipedia/commons/d/d1/MUTCD_R3-4.svg)/[`traffic_sign:backward=US:R3-4`](https://upload.wikimedia.org/wikipedia/commons/d/d1/MUTCD_R3-4.svg) or [`traffic_sign:forward=US:R3-18`](https://upload.wikimedia.org/wikipedia/commons/a/a1/MUTCD_R3-18.svg)/[`traffic_sign:backward=US:R3-18`](https://upload.wikimedia.org/wikipedia/commons/a/a1/MUTCD_R3-18.svg) depending on way direction and the direction of traffic flow this traffic sign applies to

`R3-4` | `R3-18`
-------|--------
![R3-4](https://upload.wikimedia.org/wikipedia/commons/d/d1/MUTCD_R3-4.svg) | ![R3-18](https://upload.wikimedia.org/wikipedia/commons/a/a1/MUTCD_R3-18.svg)

I have already contacted @bhousel and others from Mapbox about this common mistake. Any comments appreciated. See also #354.
