### ISSUE TITLE
Mapping missing turn restriction in top US cities

### ISSUE THREAD

**Issue by jinalfoflia** [mapbox/mapping#354]
![503039533_eee82be71a_o](https://user-images.githubusercontent.com/25571355/38264394-aa0c9cf0-3727-11e8-8514-403e92063402.jpg)

**Objective:** Map missing turn restrictions in the [200 largest US cities](https://en.wikipedia.org/wiki/List_of_United_States_cities_by_population).

**Workflow:** We'll be using the iD workflow laid out in the [adding turn restrictions](https://www.mapbox.com/mapping/adding-turn-restrictions/) documentation.

cc: @shvrm @maning @srividyacb @mikelmaron

**Comment by GITNE** [comment]
Guys, before you run off mindlessly to the job, please be aware of what you are actually mapping: **Turn restrictions** or **traffic signs** denoting turn restrictions. In OpenStreetMap terms these are two totally different concepts!

* Traffic signs (`traffic_sign=*`) **denote** the **legal situation on the road**.
* Turn restrictions (`type=restriction`) **model** the **flow of traffic**.

Most importantly: **DO NOT** add default turn restrictions. This especially pertains to `restriction=no_u_turn` restrictions on single way junctions. Hence, do not add turn restriction relations with identical members in the `to` and `from` roles, like in this [**bad example**](https://www.openstreetmap.org/relation/8169604). This kind of `restriction=no_u_turn` restriction is the **default**.

In these cases, if you still want to add data about this turn restriction to OSM—because it is verifiably (via Mapillary etc) signed—then map with:

* [`traffic_sign=US:R3-4`](https://upload.wikimedia.org/wikipedia/commons/d/d1/MUTCD_R3-4.svg) or [`traffic_sign=US:R3-18`](https://upload.wikimedia.org/wikipedia/commons/a/a1/MUTCD_R3-18.svg) with a node on the way
* `direction=forward`/`backward` depending on way direction and the direction of traffic flow the traffic sign applies to

alternatively

* [`traffic_sign:forward=US:R3-4`](https://upload.wikimedia.org/wikipedia/commons/d/d1/MUTCD_R3-4.svg)/[`traffic_sign:backward=US:R3-4`](https://upload.wikimedia.org/wikipedia/commons/d/d1/MUTCD_R3-4.svg) or [`traffic_sign:forward=US:R3-18`](https://upload.wikimedia.org/wikipedia/commons/a/a1/MUTCD_R3-18.svg)/[`traffic_sign:backward=US:R3-18`](https://upload.wikimedia.org/wikipedia/commons/a/a1/MUTCD_R3-18.svg) depending on way direction and the direction of traffic flow the traffic sign applies to

`R3-4` | `R3-18`
-------|--------
![R3-4](https://upload.wikimedia.org/wikipedia/commons/d/d1/MUTCD_R3-4.svg) | ![R3-18](https://upload.wikimedia.org/wikipedia/commons/a/a1/MUTCD_R3-18.svg)

I have already contacted @bhousel and few others from Mapbox about this common mistake. Any comments appreciated.

**Comment by 1ec5** [comment]
> This kind of restriction=no_u_turn restriction is the default.

Just noting that this depends heavily on the jurisdiction. [In California](https://www.dmv.ca.gov/portal/dmv/detail/pubs/hdbk/turns), for example, U-turns are permitted in some circumstances unless otherwise signposted.

**Comment by danpat** [comment]
@GITNE Also flagging that the `restriction=no_u_turn` is definitely not a global default.

To add to @1ec5's California example: Victoria, Australia: https://www.vicroads.vic.gov.au/safety-and-road-rules/road-rules/a-to-z-of-road-rules/turning (where I grew up) - u-turns at random spots on the road are generally permitted except under a few limited circumstances, *and* where specific signage prohibits them.

The defaults in Alberta, Canada are almost the inverse of this http://www.transportation.alberta.ca/2000.htm - notably no u-turns at intersections unless specifically posted as permitted.

I'm not sure how this data can be captured for routing algorithms (note: I'm a developer who works on the open source OSRM and Valhalla routing engines for a living) *without* mapping it, but I'm open to practical suggestions.  There are no magic databases of defaults anywhere that I'm aware of - if we don't map this stuff in OSM, there's no good way to know about it.
