### ISSUE TITLE
[France] Adding  level crossings

### ISSUE THREAD

**Issue by vladaboitsik** [mapbox/mapping#375]
**Background**

Based on the data published by the government ([link](https://data.sncf.com/explore/dataset/liste-des-passages-a-niveau/map/?basemap=osmtransport&location=19,48.4998,1.6114)) our team found out that part of the level crossings were not mapped or mapped incorrectly in the OSM. We’re going to fix it. We are not going to add crossings to the disused / abandoned railway track. Anyone can use government data and check / expand existing level crossings mapping in France.
There's a [link ](https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities/Adding_level_crossings_in_France)to the OSM Wiki page.

**Edits**

We are going to check places where, according to our observations, the data in the OSM do not contain the appropriate tagging, or where the tagging does not match the data provided by the government.
We will add missing _railway=level_crossing_ tag or change inaccurate tagging on the nodes where railways cross roads on the same-grade level.

**Contact person**

We welcome feedback, suggestions, and insights from local mappers. If you have questions about this work, or a specific edit by our team, please reach out to Vlada at vlada.boitsik@mapbox.com or post a comment in a changeset.

**Goal of the activity**

To improve the quality of the map by adding level crossings and fixing mistakes.

**Timeframe**

We are going to start at the beginning of the next week.

**A unique hashtag**

We will use the hashtag **#mbx_lvlcros_fr**

**Any non-standard tools and data sources used, and their usage conditions**

We use common OSM editors (iD, JOSM) and Bing, Esri, Maxar satellite imagery and other imagery available to OSM community as well as street level photos such as Mapilary/KartaView to edit OSM data.

**Geojson file**

Data provided by government - [link](https://data.sncf.com/explore/dataset/liste-des-passages-a-niveau/map/?basemap=osmtransport&location=19,48.4998,1.6114)

@legain @Andygol @abrohood @shvrm @lukasmartinelli @mikelmaron

**Comment by PanierAvide** [comment]
Hello,

Thanks for reaching the community before starting. Although dataset seem to be up-to-date, some level crossing are still referenced in it despite being remove from ground. In fact there was during last years an effort made by rail network company to destruct some level crossing to make roads safer and allowed train speed higher.

A real world example, this one is preset in open data but was destructed years ago (therefore not present in OSM) : https://data.sncf.com/explore/dataset/liste-des-passages-a-niveau/map/?basemap=osmtransport&location=17,48.14073,-1.88129

I highly recommended using "[Bd Ortho](https://raw.githubusercontent.com/osmlab/editor-layer-index/d5bab4f6f6c1a15b9e83d683313570f17dc7fcf7/sources/europe/fr/BDOrthoIGN.geojson)" imagery from IGN (national geographic institute), combined with Maxar Premium which may be more up-to-date on certain areas.

If doubt persist, please create a list of features to check and submit it to our community, in order to let us do ground survey.

Best regards.

**Comment by vladaboitsik** [comment]
@PanierAvide thanks a lot for your note! It will be helpful.

**Comment by overflorian** [comment]
Hi, thanks for this great initiative.
I forwarded your proposal to the SNCF department in charge of publishing this dataset. Indeed it appears that it is out-of-date, therefore I requested an update that should be useful to you.

**Comment by vladaboitsik** [comment]
Hi @overflorian !
Thank you, will wait for your update.

**Comment by overflorian** [comment]
I'm just the messenger, really ;)

I had an unofficial answer with a confirmation that the current quality of the data is not great.

Also SNCF made a partnership with Waze (https://www.sncf.com/fr/reseau-expertises/reseau-ferroviaire/sncf-reseau/waze-signale-passages-a-niveau) so it's sure that they have the data. By law, the have to publish the latest version.

I made an official request by email and also hope that my Twitter message with be massively RT (https://twitter.com/overflorian/status/1370359726958116865)

**Comment by vladaboitsik** [comment]
@overflorian it's great, thanks a lot for your support!)

**Comment by overflorian** [comment]
Hi,
I had a reply from SNCF: they won't publish any new dataset until August 2021.
Therefore this dataset is for sure, the most up-to-date available: https://data.sncf.com/explore/dataset/liste-des-passages-a-niveau
I'm confident that Waze also uses it.

Please note that we updated this Osmose consequently : https://osmose.openstreetmap.fr/fr/errors/?item=8060 (thanks @frodrigo!)
As you can see, there is a slight decrease of the number of item left to integrate:
![image](https://user-images.githubusercontent.com/11553211/111344472-aeb38780-867c-11eb-906c-c95fcc24f34c.png)

That is because we used to monitor an older dataset ([this one](https://www.data.gouv.fr/fr/datasets/liste-des-passages-a-niveau/)).
Therefore you can use this Osmose analysis to support your project and map the ~3500 objects still missing.

Regards

**Comment by vladaboitsik** [comment]
Today we finished reviewing and adding missing level crossing in France. 
We were able to improve data about level crossing by adding 519 missing items, fixing 133 outdated or incorrectly tagged level crossings. We identified that in 433 cases data were outdated and in 56 cases level crossing were already tagged as disused or coordinates of them were displaced. Fix-ratio has comprised 57.12%.

We did not add level crossing on railways tracks that were tagged as disused/abandoned in OSM (~3k items).
There's a geojson files with the results [link](https://gist.github.com/Andygol/23d924910e1e1127751825be6621dfd3)
Thanks a lot to community for supporting this project! Due to it maybe we'll continue this project after August when new dataset will be published.

![image](https://user-images.githubusercontent.com/60132467/111641382-282eaf80-880e-11eb-852a-8760d5838f43.png)

**Comment by PanierAvide** [comment]
Thanks for this very detailed feedback, and also improvements made to OSM :+1:

**Comment by overflorian** [comment]
Hi,
In the meantime, I have published the dataset over the government open data website: https://www.data.gouv.fr/fr/datasets/passages-a-niveaux-issus-dopenstreetmap
We publish every dataset that we are proud of, expecialy when the quality is better than in the original dataset.

For now it uses overpass to generate the data, so it's very very slow, and it could make the user believe that the data doesn't exist.
The french community is currently adressing the issue: @TANK2003 will develop a dedicated export module for https://github.com/data-osm (used for https://demo.openstreetmap.fr) that we can use for every dataset to export to data.gouv.fr
Regards

**Comment by vladaboitsik** [comment]
Hi @overflorian! 
Thanks for doing that and announcing to us.

**Comment by TANK2003** [comment]
Hello, i have add Level crossings in OSMData, to 
- View it : https://demo.openstreetmap.fr/map?profil=1&layers=634,11,layer
- To download as shapefile : [link](https://ws.dataosm.info/api/group/download/?provider_vector_id=undefined&table_id=undefined&provider_vector_id_target=634&driver=shp)

**Comment by vladaboitsik** [comment]
Hi @TANK2003
Great news, thank you!
